server:
  port: ${APPLICATION_PORT:18083}

netty:
  local:
    addr: ${NETTY_LOCAL_ADDR:192.168.0.125}
    port: ${NETTY_LOCAL_PORT:7878}
  remote:
    addr: ${NETTY_REMOTE_ADDR:169.254.65.221}
    port: ${NETTY_REMOTE_PORT:7880}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${ORACLE_URL:192.168.1.65:1521:orcl}
    username: ${ORACLE_USERNAME:CONN}
    password: ${ORACLE_PASSWORD:123456}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 10000
      read-only: false
  application:
    name: conn-netty-service



