server:
  port: ${APPLICATION_PORT:18083}

netty:
  local:
    addr: ${NETTY_LOCAL_ADDR:127.0.0.1}
    port: ${NETTY_LOCAL_PORT:7878}
  remote:
    addr: ${NETTY_REMOTE_ADDR:127.0.0.1}
    port: ${NETTY_REMOTE_PORT:7879}
  # 是否检测心跳 0否 1是
  checkHeartBeat: ${HEART_BEAT_CHECK:0}
  # 向外发送的心跳频率,默认120秒发一次
  heartFPS: ${HEART_SNED_FPS:120000}
  # 记录之间间隔时间,单位毫秒
  sendWaitTime: ${SEND_WAIT_TIME:5000}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${ORACLE_URL:192.168.1.65:1521:orcl}
    username: ${ORACLE_USERNAME:CONN}
    password: ${ORACLE_PASSWORD:123456}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 10000
      read-only: false
  application:
    name: conn-netty-service