netty:
  local:
    port: 7878
  remote:
    addr: 192.168.1.222
    port: 7879

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.61:3306/acs?characterEncoding=utf-8&useSSL=false
    username: acs
    password: acs2018
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 10000
      read-only: false
  application:
    name: as-manager-service

ibm:
  mq:
    queue-manager: TEST.QM
    conn-name: 192.168.1.66(1414)
    channel: SYSTEM.DEF.SVRCONN
    user: mqm
    password: mqm
    client-id: qustMqJms66v9
  recv:
    queue:
      q1: WIN.LUX.Q


