server:
  port: 8082

netty:
  local:
    addr: 192.168.0.125
    port: 7878
  remote:
    addr: 192.168.0.104
    port: 7879

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.61:3306/acs?characterEncoding=utf-8&useSSL=false
    username: acs
    password: acs2018
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 10000
      read-only: false
  application:
    name: conn-netty-service



